name: Run packer build on a template file
#Actions trigger on push to main branch under ami directory
on:
  push:
    branches:
        - 'main'
    paths:
        -  './ami'
#Job below runs packer build on the packer build file
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'ami.json.pkr.hcl'
          workingDir: 'ami'
          #varFile: 'variables.json'
#Secrets and regions are defined in the Github environment and marked sensitive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: us-west-1